import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.5.1'
 *
 * Metadata
 * Id: 31a050de-afc6-491b-9f37-d7598dd03bb0
 * Codename: metadata
 */
export type Metadata = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: 89178839-fb37-4a24-8617-a835302d3a33
   * Codename: metadata__title
   */
  metadataTitle: Elements.TextElement;

  /**
   * Description (text)
   * Required: true
   * Id: 23c454e7-3c43-43de-8047-51dbcae68e75
   * Codename: metadata__description
   */
  metadataDescription: Elements.TextElement;
}>;
